avoid turning MemberAccess expressions of literal types into Constants
AutoMapper/AutoMapper.Extensions.ExpressionMapping pull request #123
Opened 2021-09-03 16:30 UTC by csboling

Fixes #122 by checking if member expressions are literal types, in which case they don't need mapping. This avoids creating a constant (which can't be lifted to an SQL parameter) from a member access expression such as a local variable reference the expression closes over (which can).

2021-09-04 10:04 UTC, BlaiseD requested changes
Please add a separate test method.

2021-09-04 10:04 UTC, BlaiseD commented on tests/AutoMapper.Extensions.ExpressionMapping.UnitTests/XpressionMapper.Structs.Tests.cs
> +            Assert.Equal(ExpressionType.MemberAccess, mappedrhs.NodeType);
Best to remove the changes to this test and add a new one e.g.

```c#
        [Fact]
        public void Ignore_member_expressions_where_type_is_literal_and_node_type_is_constant()
        {
            // Arrange
            var config = new MapperConfiguration(c =>
            {
                c.CreateMap<GarageModel, Garage>()
                    .ReverseMap()
                        .ForMember(d => d.Color, opt => opt.MapFrom(s => s.Truck.Color));
                c.CreateMap<TruckModel, Truck>()
                    .ReverseMap();
            });

            config.AssertConfigurationIsValid();
            var mapper = config.CreateMapper();

            GarageModel garage = new GarageModel { Color = "Blue", Truck = new TruckModel { Color = "Red", Year = 1999 } };
            Expression<Func<GarageModel, bool>> filter = m => m.Color == garage.Color;

            //Act
            var mappedFilter = mapper.MapExpression<Expression<Func<Garage, bool>>>(filter);
            var mappedrhs = ((BinaryExpression)mappedFilter.Body).Right;

            //Assert
            Assert.Equal(ExpressionType.MemberAccess, mappedrhs.NodeType);
        }
```

2021-09-04 20:58 UTC, csboling commented
Added a separate test method.

This patch would be much appreciated in a patch version release to address a memory leak in my application, not sure the best way to cherry-pick this and maybe ship a 4.1.2 package. If that's a pain or undesirable I can also apply this change to a fork/submodule for the time being but I would guess that other applications making heavy use of dynamic queries are also affected by this.

2021-09-05 13:06 UTC, merged

2021-09-05 13:12 UTC, BlaiseD commented
For a release you can PR [branch v4.1.2](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/tree/v4.1.2).  It's based on v4.1.1 - and targets AutoMapper v 10.1.1. 

The master branch depends on a not yet released version of AutoMapper.