Fix enumerator not disposed when arbitrary projection is enumerated
AutoMapper/AutoMapper.Extensions.ExpressionMapping pull request #132
Opened 2022-02-20 07:43 UTC by acjh

Let's directly `foreach` the enumerable, which automatically disposes the enumerator.
Reference: [https://stackoverflow.com/questions/4982396/does-foreach-automatically-call-dispose](https://stackoverflow.com/q/4982396/8601760)

The case concerned:

```c#
// case #2: query is arbitrary ("manual") projection
// example: users.UseAsDataSource().For<UserDto>().Select(user => user.Age).ToList()
// in case an arbitrary select-statement is enumerated, we do not need to map the expression at all
// and can safely return it
```

Should* fix [https://stackoverflow.com/questions/71161821/getting-odata-dto-automapper-and-unitofwork-to-play-nicely-in-aspnetboilerplate](https://stackoverflow.com/q/71161821/8601760):

> System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.

*As per https://github.com/AutoMapper/AutoMapper/discussions/3904, I'm unable to build this project locally.
I think the existing test `Map_select_method` covers this code path, to verify that there's no regression from this change.
I can add a test `Map_select_method_should_dispose_enumerator` if desired, but I need an assist to build this project first.

# Backport request

Kindly backport to 4.x, so that this can be used in the same project that depends on AutoMapper.Collection, which does not support AutoMapper 11.x.
Reference: https://github.com/AutoMapper/AutoMapper.Collection/issues/162

2022-02-21 10:38 UTC, BlaiseD requested changes
Please add a test which fails for v5.0.0 and passes with the new changes.

2022-02-21 13:16 UTC, acjh commented
@BlaiseD Thanks for your response. As mentioned in the PR description, I need an assist to build this project first.

2022-02-21 13:53 UTC, BlaiseD commented
> @BlaiseD Thanks for your response. As mentioned in the PR description, I need an assist to build this project first.

The [CI and Release](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/actions) builds work - maybe do a web search for the issue you're running into?

2022-02-22 16:33 UTC, acjh commented
@BlaiseD I have added the test.

2022-02-22 19:39 UTC, BlaiseD approved these changes

2022-02-22 19:45 UTC, merged

2022-02-22 19:45 UTC, BlaiseD commented
Thanks

2022-02-23 01:11 UTC, acjh commented
Regarding the backport request to 4.x, should I submit a separate PR or will you handle that?

2022-02-23 10:38 UTC, BlaiseD commented
You may PR [v41.4](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/tree/v4.1.4) with the changes from #132 - we can release a v4.1.4 targeting AutoMapper v10.1.1.

Not possible with v5 because this library targets AutoMapper v11.