Fix exceptions with generic source types
AutoMapper/AutoMapper.Extensions.ExpressionMapping pull request #91
Opened 2020-10-14 18:56 UTC by mycroes

Today I ran into issues when mapping generic source types with `UseAsDataSource()`. I noticed `ExpressionMapper.VisitAllParametersExpression` was substituting the source type for it's generic argument when trying to find a match, which of course breaks the matching.

I changed the method to only take the generic type argument if the type implements `IEnumerable<>`, because I'm assuming what this logic is for. All tests still pass, so I'm assuming all is still fine. I also added a test which breaks without this change.

2020-10-14 19:07 UTC, mycroes commented
Seems to me CI build is failing due to misconfiguration, hope you can look into this PR shortly.

2020-10-14 19:40 UTC, BlaiseD requested changes
Requested a couple of changes.  Thanks.

2020-10-14 19:40 UTC, BlaiseD commented on src/AutoMapper.Extensions.ExpressionMapping/TypeExtensions.cs
> +        public static bool IsEnumerableType(this Type type, out Type itemType)
Maybe:
```c#
public static bool IsEnumerableType(this Type type)
            => type.IsGenericType && typeof(System.Collections.IEnumerable).IsAssignableFrom(type);
```

I think your method is doing more than it need to.

2020-10-14 19:40 UTC, BlaiseD commented on src/AutoMapper.Extensions.ExpressionMapping/ExpressionMapper.cs
> +                    let a = destParamType.IsEnumerableType(out var itemType) ? itemType : destParamType
Given the recommendation in `TypeExtensions.cs`:
```c#
let a = destParamType.IsEnumerableType() ? destParamType.GetGenericElementType() : destParamType
```

2020-10-14 19:43 UTC, BlaiseD commented
Never mind the build failure - probably because the myget keys are only accessible the AutoMapper repositories.

2020-10-14 19:54 UTC, mycroes commented
Hi @BlaiseD, I must admit I didn't check your suggestion before I implemented mine (which basically ensures that the generic argument of the `IEnumerable<>` implementation is used), but following your suggestions results in 27 failed tests (all across the board).

2020-10-14 19:56 UTC, mycroes commented
Sorry, that's incorrect, not sure what I messed up, but 3 other tests fail with your suggestion.

2020-10-15 19:35 UTC, BlaiseD commented
Worked for me.  With the code from your branch, the only changes were:
```c#
        public static bool IsEnumerableType(this Type type)
            => type.IsGenericType && typeof(System.Collections.IEnumerable).IsAssignableFrom(type);

        //public static bool IsEnumerableType(this Type type, out Type itemType)
        //{
        //    itemType = type.GetInterfaces()
        //        .FirstOrDefault(t => t.GetGenericTypeDefinitionIfGeneric() == typeof(IEnumerable<>))
        //        ?.GetGenericArguments()[0];

        //    return itemType != null;
        //}
```
 and
```c#
                    let a = destParamType.IsEnumerableType() ? destParamType.GetGenericElementType() : destParamType
                    //let a = destParamType.IsEnumerableType(out var itemType) ? itemType : destParamType
```

Or what am I missing.

2020-10-15 19:57 UTC, mycroes commented
My bad, messed up big time 😉 I used `GetElementType()` instead of `GetGenericElementType()`, which then results in the 3 failed cases... Applied suggested changes.

2020-10-15 22:12 UTC, BlaiseD approved these changes

2020-10-15 22:13 UTC, merged

2020-10-21 08:42 UTC, mycroes commented
Hi @BlaiseD, is there any timeline on a next release? We're currently using a local build to work around the issue fixed with this PR, but we'd prefer to use the upstream release again.

2020-10-21 09:30 UTC, BlaiseD commented
I'm sure it's part of [4.0.2-preview-2.](https://www.nuget.org/packages/AutoMapper.Extensions.ExpressionMapping/4.0.2-preview-2).

You can compare releases [here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/releases).

2020-10-21 09:40 UTC, mycroes commented
Thanks, I didn't notice there was a preview release. I'm really leaving a good impression of my analytic skills here here 😉

2020-10-21 10:13 UTC, BlaiseD commented
I'd usually leave a note in the issue or PR - didn't this time.  BTW there's also a [MyGet](https://myget.org/gallery/automapperdev) package which gets the CI build.